# Generated by Django 5.0.7 on 2024-09-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_gender_remove_profile_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalAttributes',
        ),
    ]
