# Generated by Django 5.0.7 on 2024-09-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_physicalattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin_tone',
            field=models.CharField(choices=[('LT', 'Light'), ('MD', 'Medium'), ('DK', 'Dark')], default='LT', max_length=2),
        ),
    ]
