# Generated by Django 5.0.7 on 2024-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='waist',
            field=models.FloatField(null=True),
        ),
    ]
