# Generated by Django 5.0.7 on 2024-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_wardrobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_tone',
            field=models.CharField(choices=[('EF', 'Extremely Fair Skin'), ('OS', 'Olive Skin'), ('MS', 'Medium Skin Undertone'), ('NS', 'Neutral Skin Undertone'), ('BS', 'Brown Skin'), ('DK', 'Dark Skin')], default='EF', max_length=2),
        ),
    ]
