# Generated by Django 5.0.7 on 2024-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_skin_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Judge', 'Judge'), ('Leader', 'Leader'), ('Player', 'Player')], default='Player', max_length=6),
        ),
    ]
