# Generated by Django 5.0.7 on 2024-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_player_id_user_points_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Wardrobe',
        ),
    ]
