# Generated by Django 5.0.7 on 2024-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_wardrobe_user_delete_profile_delete_wardrobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
