# Generated by Django 5.0.7 on 2024-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='super_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
