# Generated by Django 5.0.7 on 2024-10-27 08:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_team_team_team_super_score_team_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(blank=True, default=account.models.generate_tournament_id, max_length=50, unique=True)),
                ('tournament_name', models.CharField(default='Tournament Name', max_length=100)),
                ('events', models.JSONField(default=list)),
                ('games', models.JSONField(default=dict)),
            ],
        ),
    ]
