# Generated by Django 5.0.7 on 2024-10-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='games',
            new_name='game_types',
        ),
    ]
